=== onoyoko/autosite/ autosite --username DJDataB@gmail.com/automaticsitev2.5/v2.5/data xml/shop/Acatalog_V01.dtd
<?xml version="1.0" encoding="UTF-8" ?>
	<!ELEMENT catalog(title,product*)>
	<!ELEMENT product(id,title,description,img,price,barcode)>
	<!-- alert use no paswords in the link-->
	<!ELEMENT id(#PCDATA)>
	<!ELEMENT title(#PCDATA)>
	<!ELEMENT description(#PCDATA)>
	<!ELEMENT img(#PCDATA)>	
	<!ELEMENT price(#PCDATA)>
	<!ELEMENT barcode(#PCDATA)>

=== onoyoko/autosite/ autosite --username DJDataB@gmail.com/autositeV2.6/data xml/shop/catalog3.xml
<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE catalog SYSTEM "Acatalog_V01.dtd" >

<catalog>
	<title>mijn eerst catalog</title>
	<product>
		<id>eerste product</id>
		<title>PRODUCT 1</title>
		<description>tja dat was het eerst product</description>
		<img>tja dat was het eerst product</img>
		<price>tja dat was het eerst product</price>
	</product>
	<product>
		<id>tweede product</id>
		<title>PRODUCT 2</title>
		<description>tja dat was het tweede product</description>
		<img>tja img tweede product</img>
		<price>tja €€ product</price>
		<test>ff</test>
	</product>
</catalog>
